controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    mecanum_drive_controller:
      type: diff_drive_controller/DiffDriveController

mecanum_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_joint", "rear_left_joint"]
    right_wheel_names: ["front_right_joint", "rear_right_joint"]

    wheel_separation: 0.34
    wheel_radius: 0.055

    # Odometry parameters
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2 